# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_b1de681a8ed0_key -iv $encrypted_b1de681a8ed0_iv
  -in google-cloud.json.enc -out ../google-cloud.json -d

jobs:
  include:
    - stage: Build

      name: "Testes Unitarios"
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:  # Defini o script de Teste que deve rodar toda vez que o código for alterado.
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;

    - stage: STG Deploy
      script: skip
      # Definir o Deploy no Heroku
      deploy:
       provider: heroku
       strategy: api
       api_key: $HEROKU_API_KEY
       edge: true
       app: devopslab-moisez
       on:
         branch: main

     - stage: STG TEST
       script:
          - curl https://devopslab-moisez.herokuapp.com/ | grep "Hello World" || travis_terminate 1;

    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../google-cloud.json
        project: lavdevopscloud-moisez
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lavdevopscloud-moisez.ue.r.appspot.com/ | grep "Hello World" || travis_terminate 1;

